name: dart_mux
description: A starting point for Dart libraries or applications.
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  dart_websocket:
    path: ../dart-websocket

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
